### PR TITLE
We no longer collect information on unique users so remove code.

### PR DESCRIPTION
**Pull request by koetsier**
This code is unused and can be removed

Trello: https://trello.com/c/WkNfnASe/402-remove-code-recording-unique-users

### CODE REVIEW

**Review by freesteph — APPROVED** [review]

**Review by freesteph — COMMENTED** [review]
Actually; before this goes in we should undo the scheduled tasks in TF first.

**Comment by koetsier** [comment]
> Actually; before this goes in we should undo the scheduled tasks in TF first.

I assume you mean the tasks that copy the data from the performance platform to the S3 bucket? These have to all be removed at some point when the PP is switched off. Maybe we could do them all together?

**Review by freesteph — APPROVED** [review]
awesome

**Review by robinmitra — APPROVED** [review]
👍🏼

**Pull request merged**
